# Generated by Django 4.1.1 on 2022-11-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfapp', '0002_alter_myuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='dislike',
        ),
    ]
