# Generated by Django 4.1.1 on 2022-11-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfapp', '0004_alter_posts_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='description',
            new_name='caption',
        ),
    ]
