# Generated by Django 4.1.1 on 2022-12-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfapp', '0005_rename_description_posts_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to='videos'),
        ),
    ]
